### ISSUE TITLE
建议聊天窗口独立出来，和别的页面分离

### ISSUE THREAD

**Issue by wwuddan123** [Chanzhaoyu/chatgpt-web-plus#1]
建议聊天窗口独立出来，和别的页面分离，否则一切换路由，正在生成的答案就全没了

比如AI正在回答，我点了一下左下角的“管理”，再切回来的时候因为页面刷新，答案就没了。好像额度也没减，岂不是能白嫖？

已经生成完毕的答案不受影响。

**Comment by Chanzhaoyu** [comment]
收到，谢谢
