### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by DavlamAI** [Chanzhaoyu/chatgpt-web-plus#14]
Hi Redon,
After using the plugin a month later, I got the error "ChatGPT error 429: { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }", but if using another plug would be fine. Do you think can be fixed?

**Comment by jlinux** [comment]
This is a question for ChatGPT. ChatGPT requires separate payment management for its open API interface. You may have purchased Plus membership, but you have not activated payment for the API.
