### ISSUE TITLE
请问怎么买plus版呀

### ISSUE THREAD

**Issue by yonghui666** [Chanzhaoyu/chatgpt-web-plus#18]
怎么购买，怎么付钱；能开发票吗

**Comment by spammenotinoz** [comment]
Interested in purchasing, do you have an English Version?

**Comment by yonghui666** [comment]
> Interested in purchasing, do you have an English Version?

sorry , I didnt；what_country_are_you_from

**Comment by spammenotinoz** [comment]
Thanks for the reply I am located in Australia. 
Impressed by your work.

**Comment by urmi1510799** [comment]
did you bought it? I need it but can't contact author.
