### ISSUE TITLE
这个是付费服务吗？如何付费？？

### ISSUE THREAD

**Issue by iibrat** [Chanzhaoyu/chatgpt-web-plus#5]
这个是付费服务吗？如何付费？？

**Comment by winteroo** [comment]
可以试试这个 http://yl.iisai.cn

**Comment by mmm1h** [comment]
> 可以试试这个 http://yl.iisai.cn

老哥你这网站备案了吗

**Comment by sodamnsure** [comment]
付费后大佬帮忙搭建的网站，有点粗糙，可以访问下: [https://varmsg.com](https://varmsg.com)

**Comment by tianchiguaixia** [comment]
多少钱

**Comment by WhaleKlng** [comment]
> 付费后大佬帮忙搭建的网站，有点粗糙，可以访问下: https://varmsg.com

咋买的 方便发我一份吗呵呵有偿

**Comment by sodamnsure** [comment]
> 

就是Chanzhaoyu大佬的付费服务啊，直接进qq群联系就可以了

**Comment by zhpd** [comment]
参照大佬系统开发的，可以试试这个：
演示地址：https://chatgpt-plus.app
仓库地址：https://github.com/zhpd/chatgpt-plus

**Comment by hunkjun** [comment]
> > 付费后大佬帮忙搭建的网站，有点粗糙，可以访问下: https://varmsg.com
> 
> 咋买的 方便发我一份吗呵呵有偿

我可以协助帮你搭建~

**Comment by urmi1510799** [comment]
> > > After paying, the website built by the boss is a bit rough, you can visit: https://varmsg.com
> > 
> > 
> > Is it convenient to send me a copy when I bought it? Hehe, there is a fee
> 
> I can help you build it~

where to find the code? I want to deploy it. can you help me?

**Comment by tianchiguaixia** [comment]
可以试试我的：http://www.online-gpt5.com/。出售整套源码和部署方案。只要500.
