### ISSUE TITLE
Will this open sourced?

### ISSUE THREAD

**Issue by urmi1510799** [Chanzhaoyu/chatgpt-web-plus#6]
When will code will publish? What is Q group? I'm outside of china. Is it QQ chat? or is this repository only for china? can you please clarify?

**Comment by wakefun** [comment]
> When will code will publish? What is Q group? I'm outside of china. Is it QQ chat? or is this repository only for china? can you please clarify?

This project is a commercialized version and will not be open-sourced. 'Q group' refers to [QQ](https://im.qq.com/) chat groups, where the author provides paid service support. Based on the information I have gathered, the current price for the paid version is 1499 RMB, which includes deployment services and subsequent upgrade support.
